apiVersion: v1
kind: Service
metadata:
  name: alpha-blog-service
  labels:
    app: alpha-blog
spec:
  type: NodePort
  ports:
    - targetPort: 3000
      port: 3000
      nodePort: 30008
  selector:
    app: alpha-blog
