# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ddfa90c84100c79d9bf82aacb1a2f31c68ca0667d037ab5c08b4f6e8505259c79087a5bf2e6b971d817e8f3c31c5fb8731bf1ade117f7a6e01dea05898182bec

test:
  secret_key_base: fe493601dfe8e8dfe0a564fa2eb55dd060f57fc74fcbbd62592b527b602f66615a50534c80e8b2f2d53019fa7480c6319c64245c9e38a0a920e130c454cc143a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
